---
deployment:
  tasks:
    - export DEPLOYPATH=/home/haidarah/medx_backend

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp -R * $DEPLOYPATH

    - /bin/cp -R $DEPLOYPATH/public/* /home/haidarah/public_html/

    - cd $DEPLOYPATH

    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
